#
# GitHub Action: Build and Push Docker image to Docker Hub
#
name: Build and Push Docker Image

# This action runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

# Define the jobs to run
jobs:
  build-and-push:
    # Use the latest version of Ubuntu to run the job
    runs-on: ubuntu-latest

    # Define the steps for this job
    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Set up Docker Buildx (advanced builder)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Build the Docker image and push it to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true # This tells the action to actually push the image
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/codex-backend:latest
